#ifndef MBEDTLS_CONFIG_FEATURE_GROUPS_H
#define MBEDTLS_CONFIG_FEATURE_GROUPS_H

#if defined(MBEDTLS_FG_SSL)
// Dependencies:
#define MBEDTLS_FG_HASHING
#define MBEDTLS_FG_CIPHERS
#define MBEDTLS_FG_CERTIFICATES
#define MBEDTLS_FG_NETWORKING
// Features:
#define MBEDTLS_SSL_ALL_ALERT_MESSAGES
#define MBEDTLS_SSL_ENCRYPT_THEN_MAC
#define MBEDTLS_SSL_EXTENDED_MASTER_SECRET
#define MBEDTLS_SSL_RENEGOTIATION
#define MBEDTLS_SSL_MAX_FRAGMENT_LENGTH
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_PROTO_DTLS
#define MBEDTLS_SSL_ALPN
#define MBEDTLS_SSL_DTLS_ANTI_REPLAY
#define MBEDTLS_SSL_DTLS_HELLO_VERIFY
#define MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#define MBEDTLS_SSL_DTLS_BADMAC_LIMIT
#define MBEDTLS_SSL_SESSION_TICKETS
#define MBEDTLS_SSL_EXPORT_KEYS
#define MBEDTLS_SSL_SERVER_NAME_INDICATION
#define MBEDTLS_SSL_CACHE_C
#define MBEDTLS_SSL_COOKIE_C
#define MBEDTLS_SSL_TICKET_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_SRV_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#endif /* defined(MBEDTLS_FG_SSL) */

#if defined(MBEDTLS_FG_NETWORKING)
// Dependencies:
// Features:
#define MBEDTLS_NET_C
#endif /* defined(MBEDTLS_FG_NETWORKING) */

#if defined(MBEDTLS_FG_CERTIFICATES)
// Dependencies:
#define MBEDTLS_FG_PUBLIC_KEYS
#define MBEDTLS_FG_CIPHERS
#define MBEDTLS_FG_HASHING
// Features:
#define MBEDTLS_X509_CHECK_KEY_USAGE
#define MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE
#define MBEDTLS_X509_RSASSA_PSS_SUPPORT
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRL_PARSE_C
#define MBEDTLS_X509_CSR_PARSE_C
#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CSR_WRITE_C
#endif /* defined(MBEDTLS_FG_CERTIFICATES) */

#if defined(MBEDTLS_FG_HASHING)
// Dependencies:
// Features:
#define MBEDTLS_RIPEMD160_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA512_C
#define MBEDTLS_MD_C
#define MBEDTLS_MD2_C
#define MBEDTLS_MD4_C
#define MBEDTLS_MD5_C
#endif /* defined(MBEDTLS_FG_HASHING) */

#if defined(MBEDTLS_FG_RANDOM_GENERATION)
// Dependencies:
// Features:
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_HMAC_DRBG_C
#define MBEDTLS_ENTROPY_C
#endif /* defined(MBEDTLS_FG_RANDOM_GENERATION) */

#if defined(MBEDTLS_FG_CIPHERS)
// Dependencies:
// Features:
#define MBEDTLS_AES_C
#define MBEDTLS_DES_C
#define MBEDTLD_ARC4_C
#define MBEDTLD_BLOWFISH_C
#define MBEDTLS_CAMELLIA_C
#define MBEDTLS_XTEA_C
#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define MBEDTLS_ECP_DP_BP256R1_ENABLED
#define MBEDTLS_ECP_DP_BP384R1_ENABLED
#define MBEDTLS_ECP_DP_BP512R1_ENABLED
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_ECDSA_DETERMINISTIC
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECJPAKE_C
#define MBEDTLS_ECP_C
#endif /* defined(MBEDTLS_FG_CIPHERS) */

#if defined(MBEDTLS_FG_PUBLIC_KEYS)
// Dependencies:
#define MBEDTLS_FG_SERIALIZATION
// Features:
#define MBEDTLS_PK_PARSE_EC_EXTENDED
#define MBEDTLS_PK_RSA_ALT_SUPPORT
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_PKCS1_V21
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_PKCS5_C
#define MBEDTLS_PKCS12_C
#define MBEDTLS_CIPHER_PADDING_PKCS7
#endif /* defined(MBEDTLS_FG_PUBLIC_KEYS) */

#if defined(MBEDTLS_FG_SERIALIZATION)
// Dependencies:
// Features:
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PEM_WRITE_C
#endif /* defined(MBEDTLS_FG_SERIALIZATION) */

#endif /* MBEDTLS_CONFIG_FEATURE_GROUPS_H */
